// A comprehensive list of all auditable actions in the system.
export const LogAction = {
  // User
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGIN: 'USER_LOGIN',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  // Announcements
  CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
  UPDATE_ANNOUNCEMENT: 'UPDATE_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',

  // Settings
  UPDATE_TOKEN_SETTINGS: 'UPDATE_TOKEN_SETTINGS',
  UPDATE_HISTORY_SETTINGS: 'UPDATE_HISTORY_SETTINGS',

  // Premise Management (by Owner)
  GATEKEEPER_CREATED: 'GATEKEEPER_CREATED',
  GATEKEEPER_DELETED: 'GATEKEEPER_DELETED',
  HOST_CREATED: 'HOST_CREATED',
  HOST_REMOVED: 'HOST_REMOVED',
  HOST_DEACTIVATED: 'HOST_DEACTIVATED',
  HOST_ACTIVATED: 'HOST_ACTIVATED',
  PREMISE_BLOCK_VISITOR: 'PREMISE_BLOCK_VISITOR',
  PREMISE_UNBLOCK_VISITOR: 'PREMISE_UNBLOCK_VISITOR',
  OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
  FORCE_CHECKOUT_OWNER: 'FORCE_CHECKOUT_OWNER',
  FORCE_CHECKOUT_ADMIN: 'FORCE_CHECKOUT_ADMIN',
  EMERGENCY_CONTACT_ACCESSED: 'EMERGENCY_CONTACT_ACCESSED',

  // Host/Visitor Interaction
  VISITOR_RATED: 'VISITOR_RATED',
  HOST_BLOCK_VISITOR: 'HOST_BLOCK_VISITOR',
  HOST_UNBLOCK_VISITOR: 'HOST_UNBLOCK_VISITOR',
  HOST_DELETED: 'HOST_DELETED',

  // Economy
  TOKEN_PURCHASE: 'TOKEN_PURCHASE',
  PREMISE_EXPORT_CSV: 'PREMISE_EXPORT_CSV',
  PREMISE_EXPORT_PDF: 'PREMISE_EXPORT_PDF',
  OWNER_EXPORT_CSV: 'OWNER_EXPORT_CSV',
  OWNER_EXPORT_PDF: 'OWNER_EXPORT_PDF',
  HOST_EXPORT_CSV: 'HOST_EXPORT_CSV',
  HOST_EXPORT_PDF: 'HOST_EXPORT_PDF',
  VISITOR_EXPORT_CSV: 'VISITOR_EXPORT_CSV',
  VISITOR_EXPORT_PDF: 'VISITOR_EXPORT_PDF',
  VISITOR_CHECKIN_COST: 'VISITOR_CHECKIN_COST',
  PREMISE_CHECKIN_COST: 'PREMISE_CHECKIN_COST',
  PHONE_VERIFICATION_COST: 'PHONE_VERIFICATION_COST',
  INITIAL_TOKEN_ALLOCATION: 'INITIAL_TOKEN_ALLOCATION',
  WHATSAPP_NOTIFICATION_FAILED: 'WHATSAPP_NOTIFICATION_FAILED',

  // Categories
  CREATE_PREMISE_CATEGORY: 'CREATE_PREMISE_CATEGORY',
  UPDATE_PREMISE_CATEGORY: 'UPDATE_PREMISE_CATEGORY',
  DELETE_PREMISE_CATEGORY: 'DELETE_PREMISE_CATEGORY',

  // Agent Ledger
  AGENT_COMMISSION_CREDITED: 'AGENT_COMMISSION_CREDITED',
  AGENT_PAYOUT_RECORDED: 'AGENT_PAYOUT_RECORDED',

  // Admin Read/View Actions
  VIEW_ALL_VISITS_ADMIN: 'VIEW_ALL_VISITS_ADMIN',
  VIEW_ALL_USERS_ADMIN: 'VIEW_ALL_USERS_ADMIN',
  VIEW_ALL_PREMISES_ADMIN: 'VIEW_ALL_PREMISES_ADMIN',
  VIEW_VISITOR_HISTORY_ADMIN: 'VIEW_VISITOR_HISTORY_ADMIN',
  VIEW_AGENT_LEDGER_ADMIN: 'VIEW_AGENT_LEDGER_ADMIN',

  // Owner Read/View Actions
  VIEW_PREMISE_HISTORY_OWNER: 'VIEW_PREMISE_HISTORY_OWNER',

  // Host Read/View Actions
  VIEW_HOST_HISTORY: 'VIEW_HOST_HISTORY',

  // Visitor Read/View Actions
  VIEW_VISITOR_HISTORY: 'VIEW_VISITOR_HISTORY',

  // Referral Program
  REFERRAL_WELCOME_TOKENS: 'REFERRAL_WELCOME_TOKENS',
  REFERRAL_COMMISSION_CREDITED: 'REFERRAL_COMMISSION_CREDITED',

  // Payouts
  PAYOUT_REQUESTED: 'PAYOUT_REQUESTED',
  PAYOUT_APPROVED: 'PAYOUT_APPROVED',
  PAYOUT_REJECTED: 'PAYOUT_REJECTED',

  // KYC
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_VERIFIED: 'KYC_VERIFIED',

  // Agent Management
  AGENT_DESIGNATED: 'AGENT_DESIGNATED',
  AGENT_REMOVED: 'AGENT_REMOVED',

  // Phone Verification
  PHONE_VERIFIED: 'PHONE_VERIFIED',

} as const;

export type LogActionType = (typeof LogAction)[keyof typeof LogAction];
