-- ============================================================
-- AAVIJA VMS — MASTER DATABASE SETUP
-- Auto-generated by: node scripts/rebuild-master-sql.js
-- Generated at:      2026-03-28T07:15:49.644Z
-- DO NOT EDIT MANUALLY — run rebuild-master-sql.js instead
-- ============================================================
--
-- HOW TO USE:
--   1. Create a new Supabase project
--   2. Enable extensions: pgcrypto, uuid-ossp, pg_cron
--   3. Paste this entire file in the SQL Editor and Run
--   4. Follow NEW_COUNTRY_SETUP.md for remaining config steps
-- ============================================================


-- ============================================================
-- MIGRATION: 20260315_branding_services_settings.sql
-- ============================================================

-- Migration: 20260315_branding_services_settings.sql
-- Description: Adds dynamic branding identity and third-party service template configurations.

ALTER TABLE public.settings
ADD COLUMN IF NOT EXISTS brand_name TEXT DEFAULT 'Aavija',
ADD COLUMN IF NOT EXISTS brand_tagline TEXT DEFAULT 'Visitor Management Ecosystem',
ADD COLUMN IF NOT EXISTS support_email TEXT,
ADD COLUMN IF NOT EXISTS support_phone TEXT,
ADD COLUMN IF NOT EXISTS razorpay_key_id TEXT,
ADD COLUMN IF NOT EXISTS wa_template_host_notified TEXT DEFAULT 'aavija_host_notified',
ADD COLUMN IF NOT EXISTS wa_template_payout_approved TEXT DEFAULT 'aavija_payout_approved',
ADD COLUMN IF NOT EXISTS wa_template_payout_rejected TEXT DEFAULT 'aavija_payout_rejected',
ADD COLUMN IF NOT EXISTS wa_template_kyc_verified TEXT DEFAULT 'aavija_kyc_verified',
ADD COLUMN IF NOT EXISTS wa_template_tokens_converted TEXT DEFAULT 'aavija_tokens_converted',
ADD COLUMN IF NOT EXISTS wa_template_referral_commission TEXT DEFAULT 'aavija_referral_commission',
ADD COLUMN IF NOT EXISTS wa_template_threshold_reached TEXT DEFAULT 'aavija_threshold_reached',
ADD COLUMN IF NOT EXISTS wa_template_phone_verify TEXT DEFAULT 'aavija_phone_verify',
ADD COLUMN IF NOT EXISTS wa_template_agent_assigned TEXT DEFAULT 'aavija_agent_assigned';

COMMENT ON COLUMN public.settings.brand_name IS 'The public name of the application displayed to users.';
COMMENT ON COLUMN public.settings.brand_tagline IS 'The tagline or slogan displayed in headers and PDFs.';
COMMENT ON COLUMN public.settings.razorpay_key_id IS 'Public Razorpay Key ID for client-side checkouts.';
COMMENT ON COLUMN public.settings.wa_template_host_notified IS 'WhatsApp template name for notifying hosts of arrivals.';



-- ============================================================
-- MIGRATION: 20260315_dynamic_settings.sql
-- ============================================================

-- Migration: 20260315_dynamic_settings.sql
-- Description: Adds dynamic configuration parameters for rate limits, maintenance mode, and security thresholds.

ALTER TABLE public.settings
ADD COLUMN IF NOT EXISTS auth_rate_limit INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS checkin_rate_limit INTEGER DEFAULT 100,
ADD COLUMN IF NOT EXISTS whatsapp_rate_limit INTEGER DEFAULT 500,
ADD COLUMN IF NOT EXISTS max_daily_token_purchase NUMERIC DEFAULT 1000,
ADD COLUMN IF NOT EXISTS emergency_access_timeout_mins INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS is_maintenance_mode BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS maintenance_message TEXT DEFAULT 'System is undergoing maintenance. Please try again later.';

COMMENT ON COLUMN public.settings.auth_rate_limit IS 'Max login/signup attempts per minute per IP.';
COMMENT ON COLUMN public.settings.checkin_rate_limit IS 'Max check-ins per gateway per hour.';
COMMENT ON COLUMN public.settings.whatsapp_rate_limit IS 'Max WhatsApp notifications per hour globally.';
COMMENT ON COLUMN public.settings.max_daily_token_purchase IS 'Max tokens a single user can buy in 24 hours.';
COMMENT ON COLUMN public.settings.emergency_access_timeout_mins IS 'Minutes the emergency contact is visible to gatekeepers.';
COMMENT ON COLUMN public.settings.is_maintenance_mode IS 'Global/Regional kill-switch for all database writes.';
COMMENT ON COLUMN public.settings.maintenance_message IS 'Display message during maintenance mode.';



-- ============================================================
-- MIGRATION: 20260315_ensure_block_tables_exist.sql
-- ============================================================

-- 20260315_ensure_block_tables_exist.sql
-- Description: Ensures that premise_blocked_visitors and host_blocked_visitors exist with the correct schema.
-- This handles cases where previous migrations might have failed to rename or find these tables.

DO $$ 
BEGIN
    -- 1. Ensure premise_blocked_visitors exists
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'premise_blocked_visitors') THEN
        CREATE TABLE public.premise_blocked_visitors (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            premise_id UUID NOT NULL REFERENCES public.premises(id) ON DELETE CASCADE,
            visitor_id UUID NOT NULL, -- UID from visitor
            blocked_at TIMESTAMPTZ DEFAULT now(),
            blocked_by UUID NOT NULL, -- UID of owner/admin
            visitor_name TEXT NOT NULL,
            visitor_photo_url TEXT,
            UNIQUE(premise_id, visitor_id)
        );
        -- Enable RLS
        ALTER TABLE public.premise_blocked_visitors ENABLE ROW LEVEL SECURITY;
        -- Simple policies (will be refined by consolidated setup if needed)
        CREATE POLICY "Owners can view blocks for their premises" ON public.premise_blocked_visitors
            FOR SELECT USING (EXISTS (SELECT 1 FROM public.premises p WHERE p.id = premise_id AND p.owner_id = auth.uid()));
    END IF;

    -- 2. Ensure host_blocked_visitors exists
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'host_blocked_visitors') THEN
        CREATE TABLE public.host_blocked_visitors (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            host_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            visitor_id UUID NOT NULL,
            premise_id UUID NOT NULL REFERENCES public.premises(id) ON DELETE CASCADE,
            blocked_at TIMESTAMPTZ DEFAULT now(),
            blocked_by UUID NOT NULL, -- UID of host
            visitor_name TEXT NOT NULL,
            visitor_photo_url TEXT,
            UNIQUE(host_id, visitor_id, premise_id)
        );
        -- Enable RLS
        ALTER TABLE public.host_blocked_visitors ENABLE ROW LEVEL SECURITY;
        -- Simple policies
        CREATE POLICY "Hosts can view their own blocks" ON public.host_blocked_visitors
            FOR SELECT USING (auth.uid() = host_id);
    END IF;

END $$;



-- ============================================================
-- MIGRATION: 20260315_final_stabilization.sql
-- ============================================================

-- 20260315_final_stabilization.sql
-- Description: THE ABSOLUTE MASTER REPAIR (v5). 
-- This version resolves the type mismatch (TEXT vs UUID) and ensures case-insensitive naming synchronization.

-------------------------------------------------------------------------------
-- 0. PRE-FLIGHT: Ensure counter columns exist
-------------------------------------------------------------------------------
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premises' AND LOWER(column_name) = 'gatekeeper_count') THEN
        ALTER TABLE public.premises ADD COLUMN gatekeeper_count INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premises' AND LOWER(column_name) = 'gate_count') THEN
        ALTER TABLE public.premises ADD COLUMN gate_count INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premises' AND LOWER(column_name) = 'host_count') THEN
        ALTER TABLE public.premises ADD COLUMN host_count INTEGER DEFAULT 0;
    END IF;
END $$;

-------------------------------------------------------------------------------
-- 1. CLEANUP: Drop all existing RPC versions 
-------------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.rpc_block_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_block_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_block_visitor_host(UUID, UUID, INTEGER, UUID, TEXT, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_host(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_host(UUID, UUID, UUID, INTEGER, UUID, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_block_visitor_premise(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_block_visitor_premise(UUID, UUID, INTEGER, UUID, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_premise(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_premise(UUID, UUID, INTEGER, UUID, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.get_host_blocked_list(UUID, UUID);
DROP FUNCTION IF EXISTS public.sync_user_roles_for_all();
DROP FUNCTION IF EXISTS public.repair_all_user_premise_roles();

-------------------------------------------------------------------------------
-- 2. TABLE REPAIR: Indestructible Case-Insensitive RENAME & TYPE logic
-------------------------------------------------------------------------------
DO $$ 
DECLARE
    col_rec RECORD;
BEGIN
    -- Force Fix for host_blocked_visitors
    FOR col_rec IN (SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors') LOOP
        -- RENAME Logic
        IF LOWER(col_rec.column_name) = 'visitorphotourl' AND col_rec.column_name != 'visitor_photo_url' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_photo_url';
        ELSIF LOWER(col_rec.column_name) = 'blockedat' AND col_rec.column_name != 'blocked_at' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO blocked_at';
        ELSIF LOWER(col_rec.column_name) = 'blockedby' AND col_rec.column_name != 'blocked_by' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO blocked_by';
        ELSIF LOWER(col_rec.column_name) = 'visitorname' AND col_rec.column_name != 'visitor_name' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_name';
        ELSIF LOWER(col_rec.column_name) = 'visitorid' AND col_rec.column_name != 'visitor_id' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_id';
        ELSIF LOWER(col_rec.column_name) = 'hostid' AND col_rec.column_name != 'host_id' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO host_id';
        ELSIF LOWER(col_rec.column_name) = 'premiseid' AND col_rec.column_name != 'premise_id' THEN 
            EXECUTE 'ALTER TABLE public.host_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO premise_id';
        END IF;
    END LOOP;

    -- TYPE CONVERSION Logic (Ensure everything is UUID)
    -- host_id
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'host_id' AND data_type = 'text') THEN
        ALTER TABLE public.host_blocked_visitors ALTER COLUMN host_id TYPE UUID USING host_id::UUID;
    END IF;
    -- visitor_id
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'visitor_id' AND data_type = 'text') THEN
        ALTER TABLE public.host_blocked_visitors ALTER COLUMN visitor_id TYPE UUID USING visitor_id::UUID;
    END IF;
    -- premise_id
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'premise_id' AND data_type = 'text') THEN
        ALTER TABLE public.host_blocked_visitors ALTER COLUMN premise_id TYPE UUID USING premise_id::UUID;
    END IF;
    -- blocked_by
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'blocked_by' AND data_type = 'text') THEN
        ALTER TABLE public.host_blocked_visitors ALTER COLUMN blocked_by TYPE UUID USING blocked_by::UUID;
    END IF;

    -- Repeat for premise_blocked_visitors
    FOR col_rec IN (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors') LOOP
        IF LOWER(col_rec.column_name) = 'visitorphotourl' AND col_rec.column_name != 'visitor_photo_url' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_photo_url';
        ELSIF LOWER(col_rec.column_name) = 'blockedat' AND col_rec.column_name != 'blocked_at' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO blocked_at';
        ELSIF LOWER(col_rec.column_name) = 'blockedby' AND col_rec.column_name != 'blocked_by' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO blocked_by';
        ELSIF LOWER(col_rec.column_name) = 'visitorname' AND col_rec.column_name != 'visitor_name' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_name';
        ELSIF LOWER(col_rec.column_name) = 'visitorid' AND col_rec.column_name != 'visitor_id' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO visitor_id';
        ELSIF LOWER(col_rec.column_name) = 'premiseid' AND col_rec.column_name != 'premise_id' THEN 
            EXECUTE 'ALTER TABLE public.premise_blocked_visitors RENAME COLUMN ' || quote_ident(col_rec.column_name) || ' TO premise_id';
        END IF;
    END LOOP;

    -- TYPE CONVERSION Logic for premise_blocked_visitors
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors' AND column_name = 'premise_id' AND data_type = 'text') THEN
        ALTER TABLE public.premise_blocked_visitors ALTER COLUMN premise_id TYPE UUID USING premise_id::UUID;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors' AND column_name = 'visitor_id' AND data_type = 'text') THEN
        ALTER TABLE public.premise_blocked_visitors ALTER COLUMN visitor_id TYPE UUID USING visitor_id::UUID;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors' AND column_name = 'blocked_by' AND data_type = 'text') THEN
        ALTER TABLE public.premise_blocked_visitors ALTER COLUMN blocked_by TYPE UUID USING blocked_by::UUID;
    END IF;

    -- GUARANTEE: Ensure columns EXISTS at the end
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'visitor_photo_url') THEN ALTER TABLE public.host_blocked_visitors ADD COLUMN visitor_photo_url TEXT; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'blocked_at') THEN ALTER TABLE public.host_blocked_visitors ADD COLUMN blocked_at TIMESTAMPTZ DEFAULT now(); END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'host_blocked_visitors' AND column_name = 'blocked_by') THEN ALTER TABLE public.host_blocked_visitors ADD COLUMN blocked_by UUID; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors' AND column_name = 'visitor_photo_url') THEN ALTER TABLE public.premise_blocked_visitors ADD COLUMN visitor_photo_url TEXT; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'premise_blocked_visitors' AND column_name = 'blocked_at') THEN ALTER TABLE public.premise_blocked_visitors ADD COLUMN blocked_at TIMESTAMPTZ DEFAULT now(); END IF;
END $$;

-------------------------------------------------------------------------------
-- 3. REDEFINE RPCs: Atomic Operations (All UUID & snake_case)
-------------------------------------------------------------------------------

-- 3.1 List Blocked Visitors (Host)
CREATE OR REPLACE FUNCTION public.get_host_blocked_list(p_host_id UUID, p_premise_id UUID)
RETURNS TABLE (
    id UUID, visitor_id UUID, host_id UUID, premise_id UUID, visitor_name TEXT, 
    visitor_photo_url TEXT, blocked_at TIMESTAMPTZ, blocked_by UUID
) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    RETURN QUERY
    SELECT h.id, h.visitor_id, h.host_id, h.premise_id, h.visitor_name, h.visitor_photo_url, h.blocked_at, h.blocked_by
    FROM public.host_blocked_visitors h
    WHERE h.host_id = p_host_id AND h.premise_id = p_premise_id
    ORDER BY h.blocked_at DESC;
END;
$$;

-- 3.2 Block Visitor (Premise)
CREATE OR REPLACE FUNCTION public.rpc_block_visitor_premise(
  p_premise_id    UUID,
  p_visitor_id    UUID,
  p_block_cost    INTEGER,
  p_actor_id      UUID,
  p_actor_name    TEXT,
  p_actor_role    TEXT,
  p_visitor_name  TEXT,
  p_visitor_photo TEXT,
  p_expires_at    TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_current_balance INTEGER;
BEGIN
  SELECT token_balance INTO v_current_balance FROM public.premises WHERE id = p_premise_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'error', 'Premise not found.'); END IF;
  IF v_current_balance < p_block_cost THEN RETURN jsonb_build_object('success', false, 'error', 'Insufficient tokens.'); END IF;
  UPDATE public.premises SET token_balance = v_current_balance - p_block_cost WHERE id = p_premise_id;
  INSERT INTO public.premise_blocked_visitors (visitor_id, premise_id, visitor_name, visitor_photo_url, blocked_at, blocked_by)
  VALUES (p_visitor_id, p_premise_id, p_visitor_name, p_visitor_photo, NOW(), p_actor_id)
  ON CONFLICT (visitor_id, premise_id) DO UPDATE SET visitor_photo_url = p_visitor_photo, blocked_at = NOW();
  INSERT INTO public.logs ("actorId", "actorName", "actorRole", action, description, "tokenChange", timestamp, context, "expiresAt")
  VALUES (p_actor_id, p_actor_name, p_actor_role, 'PREMISE_BLOCK_VISITOR', 'Blocked visitor ' || p_visitor_name, -p_block_cost, NOW(), jsonb_build_object('premiseId', p_premise_id), p_expires_at);
  RETURN jsonb_build_object('success', true);
END;
$$;

-- 3.3 Block Visitor (Host)
CREATE OR REPLACE FUNCTION public.rpc_block_visitor_host(
  p_host_id       UUID,
  p_visitor_id    UUID,
  p_block_cost    INTEGER,
  p_actor_id      UUID,
  p_actor_name    TEXT,
  p_actor_role    TEXT,
  p_visitor_name  TEXT,
  p_visitor_photo TEXT,
  p_premise_id    UUID,
  p_expires_at    TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_current_balance INTEGER;
BEGIN
  SELECT token_balance_visitor INTO v_current_balance FROM public.users WHERE id = p_host_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'error', 'Host profile not found.'); END IF;
  IF v_current_balance < p_block_cost THEN RETURN jsonb_build_object('success', false, 'error', 'Insufficient tokens.'); END IF;
  UPDATE public.users SET token_balance_visitor = v_current_balance - p_block_cost WHERE id = p_host_id;
  INSERT INTO public.host_blocked_visitors (visitor_id, host_id, premise_id, visitor_name, visitor_photo_url, blocked_at, blocked_by)
  VALUES (p_visitor_id, p_host_id, p_premise_id, p_visitor_name, p_visitor_photo, NOW(), p_actor_id)
  ON CONFLICT (visitor_id, host_id, premise_id) DO UPDATE SET visitor_photo_url = p_visitor_photo, blocked_at = NOW();
  INSERT INTO public.logs ("actorId", "actorName", "actorRole", action, description, "tokenChange", timestamp, context, "expiresAt")
  VALUES (p_actor_id, p_actor_name, p_actor_role, 'HOST_BLOCK_VISITOR', 'Blocked visitor ' || p_visitor_name, -p_block_cost, NOW(), jsonb_build_object('premiseId', p_premise_id), p_expires_at);
  RETURN jsonb_build_object('success', true);
END;
$$;

-------------------------------------------------------------------------------
-- 4. SIDEBAR & COUNTERS Integration
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sync_user_premise_roles_manual(p_user_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE role_map JSONB;
BEGIN
    SELECT jsonb_object_agg(p_id, roles) INTO role_map FROM (
        SELECT p_id, jsonb_agg(DISTINCT role) as roles FROM (
            SELECT premise_id as p_id, role FROM public.premise_members WHERE user_id = p_user_id
            UNION
            SELECT id as p_id, 'owner' as role FROM public.premises WHERE owner_id = p_user_id
        ) combined GROUP BY p_id
    ) t;
    UPDATE public.users SET premise_roles = COALESCE(role_map, '{}'::jsonb) WHERE id = p_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.repair_premise_counters() 
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    UPDATE public.premises p SET 
        gatekeeper_count = (SELECT count(*) FROM public.premise_members pm WHERE pm.premise_id = p.id AND pm.role = 'gatekeeper'),
        gate_count = (SELECT count(*) FROM public.premise_gates pg WHERE pg.premise_id = p.id),
        host_count = (SELECT count(*) FROM public.premise_members pm WHERE pm.premise_id = p.id AND pm.role = 'host')
    WHERE p.is_active = true;
END;
$$;

CREATE OR REPLACE FUNCTION public.master_repair_stabilization()
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE u_id UUID;
BEGIN
    PERFORM public.repair_premise_counters();
    FOR u_id IN SELECT id FROM public.users LOOP PERFORM public.sync_user_premise_roles_manual(u_id); END LOOP;
END;
$$;

-- GO
SELECT public.master_repair_stabilization();



-- ============================================================
-- MIGRATION: 20260315_fix_blocked_tables.sql
-- ============================================================

-- 20260315_fix_blocked_tables.sql
-- Fixes the discrepancy between the schema (premise_blocks) and RPCs/Service (premise_blocked_visitors)

DO $$ 
BEGIN
    -- Rename premise_blocks if it exists
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'premise_blocks') THEN
        ALTER TABLE public.premise_blocks RENAME TO premise_blocked_visitors;
    END IF;

    -- Rename host_blocks if it exists
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'host_blocks') THEN
        ALTER TABLE public.host_blocks RENAME TO host_blocked_visitors;
    END IF;

    -- Ensure column names match what the RPC expects
    -- The schema has "premiseId", "visitorId", "visitorName" (camelCase)
    -- The RPC expects "premise_id", "blockedAt", "blockedBy", "visitorName", "visitorPhotoUrl"
    
    -- standardise premise_blocked_visitors
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'premise_blocked_visitors') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='premise_blocked_visitors' AND column_name='premise_id') THEN
            ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "premiseId" TO premise_id;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='premise_blocked_visitors' AND column_name='blockedAt') THEN
            ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "createdAt" TO "blockedAt";
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='premise_blocked_visitors' AND column_name='visitorPhotoUrl') THEN
            ALTER TABLE public.premise_blocked_visitors ADD COLUMN "visitorPhotoUrl" TEXT;
        END IF;
        -- Ensure PK is (id, premise_id) to match the RPC's ON CONFLICT
        -- But schema had id as surrogate PK. We need to adjust.
        ALTER TABLE public.premise_blocked_visitors DROP CONSTRAINT IF EXISTS premise_blocks_pkey;
        -- Assuming id in RPC p_visitor_id is the visitor's UUID
    END IF;

    -- standardise host_blocked_visitors
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'host_blocked_visitors') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='host_blocked_visitors' AND column_name='host_id') THEN
            ALTER TABLE public.host_blocked_visitors RENAME COLUMN "hostId" TO host_id;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='host_blocked_visitors' AND column_name='blockedAt') THEN
            ALTER TABLE public.host_blocked_visitors RENAME COLUMN "createdAt" TO "blockedAt";
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='host_blocked_visitors' AND column_name='visitorPhotoUrl') THEN
            ALTER TABLE public.host_blocked_visitors ADD COLUMN "visitorPhotoUrl" TEXT;
        END IF;
    END IF;

END $$;



-- ============================================================
-- MIGRATION: 20260315_fix_gates_schema.sql
-- ============================================================

-- 20260315_fix_gates_schema.sql
-- Description: Adds missing description column to premise_gates table.

ALTER TABLE public.premise_gates 
ADD COLUMN IF NOT EXISTS description TEXT;

-- Update search path for security
ALTER TABLE public.premise_gates SET SCHEMA public;



-- ============================================================
-- MIGRATION: 20260315_gate_auditing.sql
-- ============================================================

-- Add gate tracking to visits table
ALTER TABLE public.visits 
ADD COLUMN IF NOT EXISTS checkin_gate_id UUID REFERENCES public.premise_gates(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS checkout_gate_id UUID REFERENCES public.premise_gates(id) ON DELETE SET NULL;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_visits_checkin_gate ON public.visits(checkin_gate_id);
CREATE INDEX IF NOT EXISTS idx_visits_checkout_gate ON public.visits(checkout_gate_id);



-- ============================================================
-- MIGRATION: 20260315_host_block_premise_logic.sql
-- ============================================================

-- Migration: Premise-Specific Host Blocklist
-- Description: Adds premise_id to host_blocked_visitors and updates RPCs for premise-level granularity.

-- 1. Add premise_id to host_blocked_visitors
ALTER TABLE public.host_blocked_visitors
ADD COLUMN IF NOT EXISTS premise_id TEXT;

-- 2. Update existing data (optional, but good for consistency)
-- If we can derive premise_id from somewhere, we should. 
-- But since it was global before, it's hard to know which premise it was for.
-- We'll leave them as NULL or set to a default if known.

-- 3. Update the unique constraint/primary key
-- First, remove current primary key if it exists on (id, host_id)
-- Note: In Supabase, the table might have a different PK. Let's assume (id, host_id) based on the ON CONFLICT clause.
DO $$ 
BEGIN
    -- Check if constraint exists and drop it
    -- We'll use a unique index for the ON CONFLICT clause if it's not the PK.
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'host_blocked_visitors_pkey') THEN
        -- If it's the PK, we might need to handle it differently.
        -- For now, let's just make sure we have a unique index on (id, host_id, premise_id)
        NULL;
    END IF;
END $$;

-- Ensure we have a unique index for the new logic
-- We drop the old one if it exists (assuming it was on id, host_id)
DROP INDEX IF EXISTS host_blocked_visitors_id_host_id_idx;
CREATE UNIQUE INDEX IF NOT EXISTS host_blocked_visitors_id_host_id_premise_id_idx 
ON public.host_blocked_visitors (id, host_id, premise_id);

-- 3.5 Drop old function signatures to avoid "not unique" error
-- We drop these specifically to allow the new signatures with p_premise_id to be created uniquely.
DROP FUNCTION IF EXISTS public.rpc_block_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ);
-- Also drop any potentially overlapping ones from previous attempts
DROP FUNCTION IF EXISTS public.rpc_block_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ);
DROP FUNCTION IF EXISTS public.rpc_unblock_visitor_host(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ);

-- 4. Update rpc_block_visitor_host
CREATE OR REPLACE FUNCTION rpc_block_visitor_host(
  p_host_id       TEXT,
  p_visitor_id    TEXT,
  p_block_cost    INTEGER,
  p_actor_id      TEXT,
  p_actor_name    TEXT,
  p_actor_role    TEXT,
  p_visitor_name  TEXT,
  p_visitor_photo TEXT,
  p_premise_id    TEXT, -- Added parameter
  p_expires_at    TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_balance INTEGER;
  v_new_balance     INTEGER;
BEGIN
  -- We still deduct from the host's personal visitor token balance
  SELECT token_balance_visitor INTO v_current_balance
  FROM users
  WHERE id = p_host_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Host profile not found.');
  END IF;

  IF v_current_balance < p_block_cost THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Insufficient tokens. Action costs ' || p_block_cost || ' tokens.'
    );
  END IF;

  v_new_balance := v_current_balance - p_block_cost;

  UPDATE users SET token_balance_visitor = v_new_balance WHERE id = p_host_id;

  -- Insert block record with premise_id
  INSERT INTO host_blocked_visitors (id, host_id, premise_id, "blockedAt", "blockedBy", "visitorName", "visitorPhotoUrl")
  VALUES (p_visitor_id, p_host_id, p_premise_id, NOW(), p_actor_id, p_visitor_name, p_visitor_photo)
  ON CONFLICT (id, host_id, premise_id) DO NOTHING;

  INSERT INTO logs (
    "actorId", "actorName", "actorRole", action, description,
    "tokenChange", timestamp, context, "expiresAt"
  )
  VALUES (
    p_actor_id, p_actor_name, p_actor_role,
    'HOST_BLOCK_VISITOR',
    'Host "' || p_actor_name || '" blocked visitor "' || p_visitor_name || '" at premise ID: ' || p_premise_id || '. Cost: ' || p_block_cost || ' tokens.',
    -p_block_cost,
    NOW(),
    jsonb_build_object('premiseId', p_premise_id, 'visitorId', p_visitor_id),
    p_expires_at
  );

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 5. Update rpc_unblock_visitor_host
CREATE OR REPLACE FUNCTION rpc_unblock_visitor_host(
  p_host_id      TEXT,
  p_visitor_id   TEXT,
  p_premise_id   TEXT, -- Added parameter
  p_unblock_cost INTEGER,
  p_actor_id     TEXT,
  p_actor_name   TEXT,
  p_actor_role   TEXT,
  p_expires_at   TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_balance INTEGER;
  v_new_balance     INTEGER;
BEGIN
  SELECT token_balance_visitor INTO v_current_balance
  FROM users
  WHERE id = p_host_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Host profile not found.');
  END IF;

  IF v_current_balance < p_unblock_cost THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Insufficient tokens. Action costs ' || p_unblock_cost || ' tokens.'
    );
  END IF;

  v_new_balance := v_current_balance - p_unblock_cost;

  UPDATE users SET token_balance_visitor = v_new_balance WHERE id = p_host_id;

  -- Delete block record for the specific premise
  DELETE FROM host_blocked_visitors
  WHERE id = p_visitor_id AND host_id = p_host_id AND premise_id = p_premise_id;

  INSERT INTO logs (
    "actorId", "actorName", "actorRole", action, description,
    "tokenChange", timestamp, context, "expiresAt"
  )
  VALUES (
    p_actor_id, p_actor_name, p_actor_role,
    'HOST_UNBLOCK_VISITOR',
    'Host "' || p_actor_name || '" unblocked visitor (ID: ' || p_visitor_id || ') at premise ID: ' || p_premise_id || '. Cost: ' || p_unblock_cost || ' tokens.',
    -p_unblock_cost,
    NOW(),
    jsonb_build_object('premiseId', p_premise_id, 'visitorId', p_visitor_id),
    p_expires_at
  );

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 6. Grant execute permissions
GRANT EXECUTE ON FUNCTION rpc_block_visitor_host(TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ) TO service_role;
GRANT EXECUTE ON FUNCTION rpc_unblock_visitor_host(TEXT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ) TO service_role;

-- 7. Ensure security search path
ALTER FUNCTION rpc_block_visitor_host SET search_path = public;
ALTER FUNCTION rpc_unblock_visitor_host SET search_path = public;



-- ============================================================
-- MIGRATION: 20260315_host_verification.sql
-- ============================================================

-- Migration: Add Host Verification for Checkout
-- Date: 2026-03-15

-- 1. Add toggle to premises table
ALTER TABLE public.premises 
ADD COLUMN IF NOT EXISTS require_host_verification BOOLEAN DEFAULT false;

-- 2. Add verification tracking to visits table
ALTER TABLE public.visits 
ADD COLUMN IF NOT EXISTS host_verified_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS host_verified_by UUID REFERENCES public.users(id) ON DELETE SET NULL;

-- 3. Create index for performance
CREATE INDEX IF NOT EXISTS idx_visits_host_verified_at ON public.visits(host_verified_at);
CREATE INDEX IF NOT EXISTS idx_visits_host_verified_by ON public.visits(host_verified_by);

-- 4. Update search_premise_members to include the new column if needed (not strictly necessary here as search_premise_members is for members, not premises)

COMMENT ON COLUMN public.premises.require_host_verification IS 'When true, visitors must be verified by host before gatekeeper can checkout.';
COMMENT ON COLUMN public.visits.host_verified_at IS 'Timestamp when the host verified the meeting.';
COMMENT ON COLUMN public.visits.host_verified_by IS 'ID of the host who verified the meeting.';



-- ============================================================
-- MIGRATION: 20260315_owner_controls_and_fixes.sql
-- ============================================================

-- Migration: Owner Controls and Blocked Table Fixes
-- Description: Renames blocked visitor tables for consistency and adds host verification toggle.

-- 1. Rename premise_blocks to premise_blocked_visitors
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'premise_blocks') THEN
        ALTER TABLE public.premise_blocks RENAME TO premise_blocked_visitors;
    END IF;
END $$;

-- 2. Rename host_blocks to host_blocked_visitors
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'host_blocks') THEN
        ALTER TABLE public.host_blocks RENAME TO host_blocked_visitors;
    END IF;
END $$;

-- 3. Standardize column names if they exist with old names
-- Note: Adjust based on actual existing columns if different
DO $$ 
BEGIN
    -- For premise_blocked_visitors
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'premise_blocked_visitors' AND column_name = 'premiseId') THEN
        ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "premiseId" TO premise_id;
    END IF;
    
    -- For host_blocked_visitors
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'host_blocked_visitors' AND column_name = 'hostId') THEN
        ALTER TABLE public.host_blocked_visitors RENAME COLUMN "hostId" TO host_id;
    END IF;
END $$;

-- 4. Add require_host_verification to premises table
ALTER TABLE public.premises 
ADD COLUMN IF NOT EXISTS require_host_verification BOOLEAN DEFAULT FALSE;

-- 5. Add host_verified to visits table (to track if host met the visitor)
ALTER TABLE public.visits
ADD COLUMN IF NOT EXISTS host_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS host_verified_at TIMESTAMPTZ;

-- 6. Update search_path for security
ALTER FUNCTION public.check_rate_limit SET search_path = public;



-- ============================================================
-- MIGRATION: 20260315_pii_encryption.sql
-- ============================================================

-- Migration: 20260315_pii_encryption.sql
-- Description: Enables pgcrypto and adds PII encryption helpers.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Secure Key Management: In a real production env, this key should be in Vault/KMS.
-- For this MVP, we'll use a setting or an env variable.
-- We'll create a function to get the encryption key.

CREATE OR REPLACE FUNCTION public.get_encryption_key() RETURNS TEXT AS $$
BEGIN
    -- In production, replace 'your-secret-key' with a value from vault or a secret setting.
    RETURN 'AavijaSecureKey2026!!'; 
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Helper to encrypt PII
CREATE OR REPLACE FUNCTION public.encrypt_pii(p_data TEXT) RETURNS TEXT AS $$
BEGIN
    IF p_data IS NULL OR p_data = '' THEN
        RETURN p_data;
    END IF;
    RETURN encode(pgp_sym_encrypt(p_data, public.get_encryption_key()), 'base64');
END;
$$ LANGUAGE plpgsql IMMUTABLE SET search_path = public, extensions;

-- Helper to decrypt PII
CREATE OR REPLACE FUNCTION public.decrypt_pii(p_encoded_data TEXT) RETURNS TEXT AS $$
BEGIN
    IF p_encoded_data IS NULL OR p_encoded_data = '' THEN
        RETURN p_encoded_data;
    END IF;
    -- If it doesn't look like base64 or valid encrypted data, return as is (to handle existing plain text)
    BEGIN
        RETURN pgp_sym_decrypt(decode(p_encoded_data, 'base64'), public.get_encryption_key());
    EXCEPTION WHEN OTHERS THEN
        RETURN p_encoded_data;
    END;
END;
$$ LANGUAGE plpgsql IMMUTABLE SET search_path = public, extensions;

-- Trigger to automatically encrypt phone on insert/update
CREATE OR REPLACE FUNCTION public.trig_encrypt_user_pii() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.phone IS NOT NULL AND (TG_OP = 'INSERT' OR NEW.phone <> OLD.phone) THEN
        -- If it's already base64/encrypted (possibly from a retry/double trigger), don't double encrypt
        -- We'll just encrypt if it doesn't match the decrypt(encrypt) check or if it's plain text.
        -- For simplicity, we assume if it's being set, it's plain text from the app.
        NEW.phone := public.encrypt_pii(NEW.phone);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS tr_encrypt_user_pii ON public.users;
CREATE TRIGGER tr_encrypt_user_pii
BEFORE INSERT OR UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.trig_encrypt_user_pii();

-- View to decrypt data for internal admin use (optional)
CREATE OR REPLACE VIEW public.decrypted_users 
WITH (security_invoker = true)
AS
SELECT 
    *,
    public.decrypt_pii(phone) as decrypted_phone
FROM public.users;



-- ============================================================
-- MIGRATION: 20260315_rate_limiting.sql
-- ============================================================

-- Migration: 20260315_rate_limiting.sql
-- Description: Adds a centralized rate limiting table and RPC to enforce dynamic limits.

CREATE TABLE IF NOT EXISTS public.rate_limits (
    key TEXT PRIMARY KEY, -- e.g. "auth:192.168.1.1", "checkin:premise_123"
    request_count INTEGER DEFAULT 0,
    last_request_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    reset_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '1 minute'
);

-- Index for expiring old rate limit entries
CREATE INDEX IF NOT EXISTS idx_rate_limits_reset_at ON public.rate_limits(reset_at);

-- RPC to check and increment rate limit
CREATE OR REPLACE FUNCTION public.check_rate_limit(
    p_key TEXT,
    p_max_requests INTEGER,
    p_window_interval INTERVAL DEFAULT INTERVAL '1 minute'
) RETURNS BOOLEAN AS $$
DECLARE
    v_count INTEGER;
    v_reset_at TIMESTAMP WITH TIME ZONE;
BEGIN
    -- Upsert the rate limit entry
    INSERT INTO public.rate_limits (key, request_count, last_request_at, reset_at)
    VALUES (p_key, 1, NOW(), NOW() + p_window_interval)
    ON CONFLICT (key) DO UPDATE
    SET 
        request_count = CASE 
            WHEN public.rate_limits.reset_at < NOW() THEN 1 
            ELSE public.rate_limits.request_count + 1 
        END,
        reset_at = CASE 
            WHEN public.rate_limits.reset_at < NOW() THEN NOW() + p_window_interval 
            ELSE public.rate_limits.reset_at 
        END,
        last_request_at = NOW()
    RETURNING request_count INTO v_count;

    RETURN v_count <= p_max_requests;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Security Hardening: RLS
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

-- Deny all direct access (table is managed via SECURITY DEFINER logic)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'rate_limits' AND policyname = 'Deny all direct access'
    ) THEN
        CREATE POLICY "Deny all direct access" ON public.rate_limits FOR ALL USING (false);
    END IF;
END
$$;



-- ============================================================
-- MIGRATION: 20260315_repair_blocklist_rename.sql
-- ============================================================

-- 20260315_repair_blocklist_rename.sql
-- Description: Robust repair for blocked visitor tables, ensuring snake_case columns.

-- 1. REPAIR host_blocked_visitors
DO $$ 
BEGIN
    -- Rename columns if they exist in camelCase
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'host_blocked_visitors' AND column_name = 'blockedAt') THEN
        ALTER TABLE public.host_blocked_visitors RENAME COLUMN "blockedAt" TO blocked_at;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'host_blocked_visitors' AND column_name = 'blockedBy') THEN
        ALTER TABLE public.host_blocked_visitors RENAME COLUMN "blockedBy" TO blocked_by;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'host_blocked_visitors' AND column_name = 'visitorName') THEN
        ALTER TABLE public.host_blocked_visitors RENAME COLUMN "visitorName" TO visitor_name;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'host_blocked_visitors' AND column_name = 'visitorPhotoUrl') THEN
        ALTER TABLE public.host_blocked_visitors RENAME COLUMN "visitorPhotoUrl" TO visitor_photo_url;
    END IF;
END $$;

-- 2. REPAIR premise_blocked_visitors
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'premise_blocked_visitors' AND column_name = 'blockedAt') THEN
        ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "blockedAt" TO blocked_at;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'premise_blocked_visitors' AND column_name = 'blockedBy') THEN
        ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "blockedBy" TO blocked_by;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'premise_blocked_visitors' AND column_name = 'visitorName') THEN
        ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "visitorName" TO visitor_name;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'premise_blocked_visitors' AND column_name = 'visitorPhotoUrl') THEN
        ALTER TABLE public.premise_blocked_visitors RENAME COLUMN "visitorPhotoUrl" TO visitor_photo_url;
    END IF;
END $$;

-- 3. ENSURE RLS POLICIES USE SNAKE_CASE
-- (The migration will typically fail if policies exist with old names, but we ensure the schema cache is fresh)
NOTIFY pgrst, 'reload schema';



-- ============================================================
-- MIGRATION: 20260315_scalable_search.sql
-- ============================================================

-- RPC for searchable, paginated premise members
CREATE OR REPLACE FUNCTION search_premise_members(
    premise_id_param UUID,
    role_param TEXT DEFAULT NULL,
    search_term_param TEXT DEFAULT '',
    limit_param INT DEFAULT 50,
    offset_param INT DEFAULT 0
)
RETURNS TABLE (
    id UUID,
    premise_id UUID,
    user_id UUID,
    role TEXT,
    identity TEXT,
    gate_id UUID,
    is_active BOOLEAN,
    created_at TIMESTAMPTZ,
    user_name TEXT,
    user_email TEXT,
    user_photo_url TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pm.id,
        pm.premise_id,
        pm.user_id,
        pm.role,
        pm.identity,
        pm.gate_id,
        pm.is_active,
        pm.created_at,
        u.name as user_name,
        u.email as user_email,
        u.photo_url as user_photo_url
    FROM 
        premise_members pm
    JOIN 
        users u ON pm.user_id = u.id
    WHERE 
        pm.premise_id = premise_id_param
        AND (role_param IS NULL OR pm.role = role_param)
        AND (
            search_term_param = '' 
            OR u.name ILIKE '%' || search_term_param || '%'
            OR u.email ILIKE '%' || search_term_param || '%'
            OR pm.identity ILIKE '%' || search_term_param || '%'
        )
    ORDER BY 
        pm.created_at DESC
    LIMIT limit_param
    OFFSET offset_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Counter RPCs
CREATE OR REPLACE FUNCTION increment_gatekeeper_count(premise_id_param UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE premises 
    SET gatekeeper_count = COALESCE(gatekeeper_count, 0) + 1
    WHERE id = premise_id_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION decrement_gatekeeper_count(premise_id_param UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE premises 
    SET gatekeeper_count = GREATEST(0, COALESCE(gatekeeper_count, 0) - 1)
    WHERE id = premise_id_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;



-- ============================================================
-- MIGRATION: 20260317_fix_pgcrypto.sql
-- ============================================================

-- Migration: 20260317_fix_pgcrypto.sql
-- Description: Enables pgcrypto extension to fix "pgp_sym_encrypt does not exist" error.

-- 1. Enable pgcrypto extension
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Validate the extension is active
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto') THEN
        RAISE EXCEPTION 'pgcrypto extension could not be enabled';
    END IF;
END $$;

-- 3. Re-verify PII helper functions (just in case)
-- These should already exist from 20260315_pii_encryption.sql, 
-- but ensuring they are using public schema explicitly.

CREATE OR REPLACE FUNCTION public.encrypt_pii(p_data TEXT) RETURNS TEXT AS $$
BEGIN
    IF p_data IS NULL OR p_data = '' THEN
        RETURN p_data;
    END IF;
    RETURN encode(pgp_sym_encrypt(p_data, public.get_encryption_key()), 'base64');
END;
$$ LANGUAGE plpgsql IMMUTABLE SET search_path = public, extensions;

CREATE OR REPLACE FUNCTION public.decrypt_pii(p_encoded_data TEXT) RETURNS TEXT AS $$
BEGIN
    IF p_encoded_data IS NULL OR p_encoded_data = '' THEN
        RETURN p_encoded_data;
    END IF;
    BEGIN
        RETURN pgp_sym_decrypt(decode(p_encoded_data, 'base64'), public.get_encryption_key());
    EXCEPTION WHEN OTHERS THEN
        RETURN p_encoded_data;
    END;
END;
$$ LANGUAGE plpgsql IMMUTABLE SET search_path = public, extensions;



-- ============================================================
-- MIGRATION: 20260320_atomic_premise_approval.sql
-- ============================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- AAVIJA VMS — Atomic Premise Approval RPC
-- Run this in your Supabase SQL Editor.
-- This replaces the multi-step sequential approval with a single atomic transaction.
-- If ANY step fails, ALL changes are rolled back.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION approve_premise_application(
  p_application_id UUID,
  p_category_id UUID,
  p_admin_id UUID,
  p_admin_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_app           premise_applications%ROWTYPE;
  v_owner         users%ROWTYPE;
  v_category      premise_categories%ROWTYPE;
  v_settings      settings%ROWTYPE;
  v_premise_id    UUID := gen_random_uuid();
  v_agent_id      UUID;
  v_current_roles JSONB;
  v_updated_roles JSONB;
BEGIN
  -- ── 1. Fetch the pending application (lock it for update) ─────────────────
  SELECT * INTO v_app
  FROM premise_applications
  WHERE id = p_application_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Application not found or already processed.');
  END IF;

  -- Initialize v_agent_id after v_app is fetched
  v_agent_id := COALESCE(v_app.agent_user_id, v_app.submitted_by);


  -- ── 2. Fetch and validate category ────────────────────────────────────────
  SELECT * INTO v_category
  FROM premise_categories
  WHERE id = p_category_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Selected category not found.');
  END IF;

  -- ── 3. Fetch owner from email ──────────────────────────────────────────────
  SELECT * INTO v_owner
  FROM users
  WHERE email = v_app.owner_email;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Owner account not found for email: ' || v_app.owner_email);
  END IF;

  -- ── 4. Fetch settings ─────────────────────────────────────────────────────
  SELECT * INTO v_settings FROM settings WHERE id = 'global';

  -- ── 5. Ensure agent exists in shadow table (upsert) ───────────────────────
  IF v_agent_id IS NOT NULL THEN
    INSERT INTO agents (id, name, phone, city, commission_balance)
    VALUES (
      v_agent_id,
      COALESCE(v_app.agent_name, 'Unknown Agent'),
      '',
      COALESCE(v_app.city_name, 'Unknown'),
      0
    )
    ON CONFLICT (id) DO NOTHING;
  END IF;

  -- ── 6. Create the premise ─────────────────────────────────────────────────
  INSERT INTO premises (
    id, name, address, city, "cityId", city_state, is_active,
    owner_id, "ownerName", agent_id, "categoryId", "categoryName",
    staff, host_count, gatekeeper_count, token_balance
  ) VALUES (
    v_premise_id,
    v_app.premise_name,
    v_app.premise_address,
    COALESCE(v_app.city_name, ''),
    v_app.city_id::TEXT,
    COALESCE(v_app.city_state, 'Unknown'),
    true,
    v_owner.id,
    v_owner.name,
    v_agent_id,
    v_category.id,
    v_category.name,
    '[]'::JSONB,
    0,
    0,
    COALESCE(v_settings.starting_token_owner, 0)
  );

  -- ── 7. Update owner's premise_roles ───────────────────────────────────────
  v_current_roles := COALESCE(v_owner.premise_roles, '{}'::JSONB);
  v_updated_roles := jsonb_set(
    v_current_roles,
    ARRAY[v_premise_id::TEXT],
    COALESCE(v_current_roles->v_premise_id::TEXT, '[]'::JSONB) || '["owner"]'::JSONB
  );

  UPDATE users
  SET premise_roles = v_updated_roles
  WHERE id = v_owner.id;

  -- ── 8. Mark application as approved ───────────────────────────────────────
  UPDATE premise_applications
  SET
    status = 'approved',
    reviewed_by = p_admin_id,
    reviewed_at = NOW(),
    created_premise_id = v_premise_id
  WHERE id = p_application_id;

  -- ── 9. Return success with the new premise ID ──────────────────────────────
  RETURN jsonb_build_object(
    'success', true,
    'premise_id', v_premise_id,
    'owner_id', v_owner.id,
    'owner_phone', v_owner.phone,
    'agent_user_id', v_agent_id,
    'agent_name', v_app.agent_name,
    'agent_email', v_app.agent_email,
    'premise_name', v_app.premise_name
  );

EXCEPTION WHEN OTHERS THEN
  -- The transaction is automatically rolled back by the EXCEPTION block
  RAISE LOG 'approve_premise_application failed for application %: %', p_application_id, SQLERRM;
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- Grant execute permission to the service role
GRANT EXECUTE ON FUNCTION approve_premise_application(UUID, UUID, UUID, TEXT) TO service_role;



-- ============================================================
-- MIGRATION: 20260320_fix_premise_category_types.sql
-- ============================================================

-- Migration: 20260320_fix_premise_category_types.sql
-- Description: Updates legacy 'standard' premise category types to 'industrial' for compatibility with new UI.

UPDATE public.premise_categories
SET type = 'industrial'
WHERE type = 'standard' OR type IS NULL;



-- ============================================================
-- MIGRATION: 20260320_premise_applications.sql
-- ============================================================

-- Migration: 20260320_premise_applications.sql
-- Description: Adds the premise_applications table for the agent-driven "Apply for Premise" flow.
-- Agents submit applications; admins review and approve with one click.

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.premise_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Status lifecycle: pending → approved | rejected
    status TEXT NOT NULL DEFAULT 'pending'
        CONSTRAINT valid_status CHECK (status IN ('pending', 'approved', 'rejected')),

    -- Premise Details (filled by applicant)
    premise_name    TEXT NOT NULL,
    premise_address TEXT NOT NULL,
    city_id         UUID REFERENCES public.cities(id) ON DELETE SET NULL,
    city_name       TEXT,
    city_state      TEXT,
    category_id     UUID REFERENCES public.premise_categories(id) ON DELETE SET NULL,
    category_name   TEXT,

    -- Owner (must be existing user — we only store email and resolve on approval)
    owner_email     TEXT NOT NULL,
    owner_id        UUID, -- resolved server-side on approval

    -- Agent (auto-filled from the submitting agent's profile)
    agent_user_id   UUID REFERENCES public.users(id) ON DELETE SET NULL,
    agent_name      TEXT,
    agent_email     TEXT,

    -- Audit
    submitted_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    reviewed_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    rejection_reason TEXT,
    created_premise_id UUID, -- set after approval

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

-- 2. Enable RLS
ALTER TABLE public.premise_applications ENABLE ROW LEVEL SECURITY;

-- 3. Policies
--  Agents can submit and view their own applications
CREATE POLICY "app_insert_authed"
    ON public.premise_applications FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "app_select_own_or_admin"
    ON public.premise_applications FOR SELECT
    USING (submitted_by = (SELECT auth.uid()) OR public.is_admin());

--  Only admin can update (approve/reject)
CREATE POLICY "app_update_admin"
    ON public.premise_applications FOR UPDATE
    USING (public.is_admin());

-- 4. Index for fast pending queue lookup
CREATE INDEX IF NOT EXISTS idx_premise_applications_status
    ON public.premise_applications (status, created_at DESC);



-- ============================================================
-- MIGRATION: 20260320_premises_updated_at.sql
-- ============================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- AAVIJA VMS — Add `updated_at` column to premises for Optimistic Locking
-- Run this AFTER 20260320_atomic_premise_approval.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- Add updated_at column (auto-maintained by trigger)
ALTER TABLE public.premises
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Create a trigger function to auto-update the timestamp on any row change
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Apply the trigger specifically to premises
DROP TRIGGER IF EXISTS premises_set_updated_at ON public.premises;
CREATE TRIGGER premises_set_updated_at
  BEFORE UPDATE ON public.premises
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Backfill existing rows with a sensible default
UPDATE public.premises
SET updated_at = created_at
WHERE updated_at IS NULL;



-- ============================================================
-- MIGRATION: 20260320_universal_rls_policies.sql
-- ============================================================

-- Migration: 20260320_universal_rls_policies.sql
-- Description: Enforces Row-Level Security on ALL public tables and defines secure access policies.
-- Design Principle: DENY by default, granularly PERMIT by role and ownership.

-- 1. Helper Function for Admin Check (Cached for performance within transaction)
CREATE OR REPLACE FUNCTION public.is_admin() 
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = (SELECT auth.uid()) AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;

-- 2. Enable RLS on ALL identified tables (Idempotent)
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN (
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename NOT IN ('spatial_ref_sys') -- exclude PostGIS if exists
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

-- 3. DROP LEGACY POLICIES for Clean Slate (on core tables)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public' 
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- 4. DEFINE NEW ROBUST POLICIES

-- === [TABLE: users] ===
CREATE POLICY "users_select" ON public.users FOR SELECT USING (id = (SELECT auth.uid()) OR is_admin());
CREATE POLICY "users_update" ON public.users FOR UPDATE USING (id = (SELECT auth.uid()) OR is_admin());

-- === [TABLE: premises] ===
CREATE POLICY "premises_select" ON public.premises FOR SELECT USING (true);
CREATE POLICY "premises_insert" ON public.premises FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "premises_update" ON public.premises FOR UPDATE USING (is_admin() OR owner_id = (SELECT auth.uid()));
CREATE POLICY "premises_delete" ON public.premises FOR DELETE USING (is_admin());

-- === [TABLE: visits] ===
CREATE POLICY "visits_select" ON public.visits FOR SELECT 
USING (
  is_admin() OR 
  visitor_id = (SELECT auth.uid()) OR 
  host_id = (SELECT auth.uid()) OR
  EXISTS (SELECT 1 FROM public.premise_members WHERE user_id = (SELECT auth.uid()) AND premise_id = visits.premise_id AND role = 'gatekeeper') OR
  EXISTS (SELECT 1 FROM public.premises WHERE id = visits.premise_id AND owner_id = (SELECT auth.uid()))
);
CREATE POLICY "visits_insert" ON public.visits FOR INSERT WITH CHECK (
  is_admin() OR
  EXISTS (SELECT 1 FROM public.premise_members WHERE user_id = (SELECT auth.uid()) AND premise_id = visits.premise_id AND role = 'gatekeeper')
);
CREATE POLICY "visits_update" ON public.visits FOR UPDATE USING (
  is_admin() OR
  EXISTS (SELECT 1 FROM public.premise_members WHERE user_id = (SELECT auth.uid()) AND premise_id = visits.premise_id AND role = 'gatekeeper')
);
CREATE POLICY "visits_delete" ON public.visits FOR DELETE USING (is_admin());

-- === [TABLE: logs] ===
CREATE POLICY "logs_select" ON public.logs FOR SELECT USING (is_admin() OR "actorId" = (SELECT auth.uid()));
-- Note: Insert is handled by service role.

-- === [TABLE: settings] ===
CREATE POLICY "settings_select" ON public.settings FOR SELECT USING (true);
CREATE POLICY "settings_admin_insert" ON public.settings FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "settings_admin_update" ON public.settings FOR UPDATE USING (is_admin());
CREATE POLICY "settings_admin_delete" ON public.settings FOR DELETE USING (is_admin());

-- === [TABLE: ratings] ===
CREATE POLICY "ratings_select" ON public.ratings FOR SELECT USING (true);
CREATE POLICY "ratings_insert" ON public.ratings FOR INSERT WITH CHECK ("visitorId" = (SELECT auth.uid()) OR is_admin());
CREATE POLICY "ratings_update" ON public.ratings FOR UPDATE USING ("visitorId" = (SELECT auth.uid()) OR is_admin());
CREATE POLICY "ratings_delete" ON public.ratings FOR DELETE USING ("visitorId" = (SELECT auth.uid()) OR is_admin());

-- === [TABLE: premise_blocked_visitors] ===
CREATE POLICY "premise_blocks_access" ON public.premise_blocked_visitors FOR ALL
USING (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));

-- === [TABLE: host_blocked_visitors] ===
CREATE POLICY "host_blocks_access" ON public.host_blocked_visitors FOR ALL 
  USING (host_id = (SELECT auth.uid()) OR is_admin());

-- === [TABLE: referrals] ===
CREATE POLICY "referrals_select" ON public.referrals FOR SELECT 
  USING (referrer_id = (SELECT auth.uid()) OR referee_id = (SELECT auth.uid()) OR is_admin());

-- === [TABLE: payout_requests] ===
CREATE POLICY "payouts_select" ON public.payout_requests FOR SELECT USING (user_id = (SELECT auth.uid()) OR is_admin());
CREATE POLICY "payouts_insert" ON public.payout_requests FOR INSERT WITH CHECK (user_id = (SELECT auth.uid()));

-- === [TABLE: static data] ===
CREATE POLICY "static_read_cities" ON public.cities FOR SELECT USING (true);
CREATE POLICY "static_read_districts" ON public.districts FOR SELECT USING (true);
CREATE POLICY "static_read_states" ON public.states FOR SELECT USING (true);
CREATE POLICY "static_read_cats" ON public.premise_categories FOR SELECT USING (true);

-- === [TABLE: agents] ===
CREATE POLICY "agents_select" ON public.agents FOR SELECT USING (is_admin() OR id = (SELECT auth.uid()));
CREATE POLICY "agents_admin_insert" ON public.agents FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "agents_admin_update" ON public.agents FOR UPDATE USING (is_admin());
CREATE POLICY "agents_admin_delete" ON public.agents FOR DELETE USING (is_admin());

-- === [TABLE: agent_ledger] ===
CREATE POLICY "agent_ledger_select" ON public.agent_ledger FOR SELECT USING (is_admin() OR agent_id = (SELECT auth.uid()));
CREATE POLICY "agent_ledger_admin_insert" ON public.agent_ledger FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "agent_ledger_admin_update" ON public.agent_ledger FOR UPDATE USING (is_admin());
CREATE POLICY "agent_ledger_admin_delete" ON public.agent_ledger FOR DELETE USING (is_admin());

-- === [TABLE: announcements] ===
CREATE POLICY "announcements_select" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "announcements_admin_insert" ON public.announcements FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "announcements_admin_update" ON public.announcements FOR UPDATE USING (is_admin());
CREATE POLICY "announcements_admin_delete" ON public.announcements FOR DELETE USING (is_admin());

-- === [TABLE: checkin_tokens] ===
CREATE POLICY "tokens_select" ON public.checkin_tokens FOR SELECT USING (true);
CREATE POLICY "tokens_admin_insert" ON public.checkin_tokens FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "tokens_admin_update" ON public.checkin_tokens FOR UPDATE USING (is_admin());
CREATE POLICY "tokens_admin_delete" ON public.checkin_tokens FOR DELETE USING (is_admin());

-- === [TABLE: contact_submissions] ===
CREATE POLICY "contact_admin_access" ON public.contact_submissions FOR ALL USING (is_admin());

-- === [TABLE: premise_gates] ===
CREATE POLICY "gates_select" ON public.premise_gates FOR SELECT USING (true);
CREATE POLICY "gates_insert" ON public.premise_gates FOR INSERT WITH CHECK (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));
CREATE POLICY "gates_update" ON public.premise_gates FOR UPDATE USING (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));
CREATE POLICY "gates_delete" ON public.premise_gates FOR DELETE USING (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));

-- === [TABLE: premise_members] ===
CREATE POLICY "members_select" ON public.premise_members FOR SELECT USING (true);
CREATE POLICY "members_insert" ON public.premise_members FOR INSERT WITH CHECK (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));
CREATE POLICY "members_update" ON public.premise_members FOR UPDATE USING (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));
CREATE POLICY "members_delete" ON public.premise_members FOR DELETE USING (is_admin() OR EXISTS (SELECT 1 FROM public.premises WHERE id = premise_id AND owner_id = (SELECT auth.uid())));

-- === [TABLE: rate_limits] ===
CREATE POLICY "rate_limits_admin" ON public.rate_limits FOR ALL USING (is_admin());

-- === [TABLE: regions] ===
CREATE POLICY "regions_select" ON public.regions FOR SELECT USING (true);
CREATE POLICY "regions_admin_insert" ON public.regions FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "regions_admin_update" ON public.regions FOR UPDATE USING (is_admin());
CREATE POLICY "regions_admin_delete" ON public.regions FOR DELETE USING (is_admin());

-- === [TABLE: whatsapp_otps] ===
CREATE POLICY "whatsapp_otps_admin" ON public.whatsapp_otps FOR ALL USING (is_admin());

-- === [TABLE: invoices] ===
CREATE POLICY "invoices_select" ON public.invoices FOR SELECT USING ("userId" = (SELECT auth.uid()) OR is_admin());
CREATE POLICY "invoices_admin_insert" ON public.invoices FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "invoices_admin_update" ON public.invoices FOR UPDATE USING (is_admin());
CREATE POLICY "invoices_admin_delete" ON public.invoices FOR DELETE USING (is_admin());



-- ============================================================
-- MIGRATION: 20260323_fix_settings_schema.sql
-- ============================================================

-- Migration: 20260323_fix_settings_schema.sql
-- Description: Adds columns that are defined in application code but were missing
--              from the database schema, causing Supabase PostgREST cache errors.
--              All additions use IF NOT EXISTS and are safe to re-run.
--              Must be applied to ALL country databases (India, UAE, etc.)

-- Fix: whatsapp_phone_number_id (caused schema cache error in WhatsApp service)
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS whatsapp_phone_number_id TEXT;

COMMENT ON COLUMN public.settings.whatsapp_phone_number_id IS 'WhatsApp Cloud API Phone Number ID used as the sender for all outbound messages.';

-- Fix: Agent payout threshold (was hardcoded to 500 in token-service.ts,
--       now softcoded via Admin > Token & Economy Settings)
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS payout_threshold_agent NUMERIC DEFAULT 500;

COMMENT ON COLUMN public.settings.payout_threshold_agent IS 'Minimum commission balance an agent must accumulate before being eligible to request a withdrawal payout.';

-- Fix: Referrer payout threshold (used by referral-service)
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS payout_threshold_referrer NUMERIC DEFAULT 500;

COMMENT ON COLUMN public.settings.payout_threshold_referrer IS 'Minimum balance a referrer must accumulate before being eligible for a payout.';

-- Fix: TDS compliance fields (used by token-settings admin page but may be absent in older DBs)
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS tds_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tds_rate NUMERIC DEFAULT 10,
  ADD COLUMN IF NOT EXISTS tds_annual_exemption NUMERIC DEFAULT 30000;

COMMENT ON COLUMN public.settings.tds_enabled IS 'Whether TDS deduction is active on agent/referrer payouts.';
COMMENT ON COLUMN public.settings.tds_rate IS 'TDS percentage rate (e.g., 10 = 10%). Section 194H applies.';
COMMENT ON COLUMN public.settings.tds_annual_exemption IS 'Annual payout amount (in currency) exempt from TDS.';

-- Fix: Referral program settings (used by referral-service but may be absent in older DBs)
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS referral_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS referral_reward_tokens NUMERIC DEFAULT 10,
  ADD COLUMN IF NOT EXISTS referral_commission_rate NUMERIC DEFAULT 0.05,
  ADD COLUMN IF NOT EXISTS referral_min_purchase_tokens NUMERIC DEFAULT 50,
  ADD COLUMN IF NOT EXISTS referral_first_purchase_only BOOLEAN DEFAULT TRUE;

COMMENT ON COLUMN public.settings.referral_enabled IS 'Master switch for the referral commission program.';
COMMENT ON COLUMN public.settings.referral_reward_tokens IS 'Bonus tokens credited to a new user who signs up via referral link.';
COMMENT ON COLUMN public.settings.referral_commission_rate IS 'Fraction of purchase value credited to referrer (e.g., 0.05 = 5%).';
COMMENT ON COLUMN public.settings.referral_min_purchase_tokens IS 'Minimum tokens a referee must purchase to trigger commission.';
COMMENT ON COLUMN public.settings.referral_first_purchase_only IS 'If true, commission is only paid on the referee''s very first purchase.';

-- Fix: Token conversion rate for agent payouts
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS token_conversion_rate NUMERIC DEFAULT 1;

COMMENT ON COLUMN public.settings.token_conversion_rate IS 'How many tokens an agent receives per 1 unit of local currency when converting commission to tokens.';

-- Fix: Payout method note displayed to agents
ALTER TABLE public.settings
  ADD COLUMN IF NOT EXISTS payout_method_note TEXT;

COMMENT ON COLUMN public.settings.payout_method_note IS 'Free-text note shown to agents explaining how/when payouts are processed (e.g., Every Monday via UPI).';



-- ============================================================
-- MIGRATION: 20260327_add_action_timestamps.sql
-- ============================================================

-- Migration: 20260327_add_action_timestamps.sql
-- Description: Adds the missing action_timestamps JSONB column to public.users to fix OTP rate limiting errors.

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS action_timestamps JSONB DEFAULT '{}'::jsonb;

-- Comment for self documentation
COMMENT ON COLUMN public.users.action_timestamps IS 'Rate limiting timestamps per action type (e.g., whatsapp_otp_requests)';



-- ============================================================
-- MIGRATION: 20260328_fix_premise_cascades.sql
-- ============================================================

-- 20260328_fix_premise_cascades.sql
-- Description: Add ON DELETE CASCADE to all foreign keys referencing public.premises(id) 
-- to allow premises to be deleted along with their associated data (visits, logs, etc.)

DO $$ 
BEGIN
    -- 1. visits
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'visits_premise_id_fkey') THEN
        ALTER TABLE public.visits DROP CONSTRAINT visits_premise_id_fkey;
    END IF;
    ALTER TABLE public.visits 
    ADD CONSTRAINT visits_premise_id_fkey 
    FOREIGN KEY (premise_id) REFERENCES public.premises(id) ON DELETE CASCADE;

    -- 2. logs
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'logs_premiseId_fkey') THEN
        ALTER TABLE public.logs DROP CONSTRAINT "logs_premiseId_fkey";
    END IF;
    ALTER TABLE public.logs 
    ADD CONSTRAINT "logs_premiseId_fkey" 
    FOREIGN KEY ("premiseId") REFERENCES public.premises(id) ON DELETE CASCADE;

    -- 3. checkin_tokens
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'checkin_tokens_premise_id_fkey') THEN
        ALTER TABLE public.checkin_tokens DROP CONSTRAINT checkin_tokens_premise_id_fkey;
    END IF;
    ALTER TABLE public.checkin_tokens 
    ADD CONSTRAINT checkin_tokens_premise_id_fkey 
    FOREIGN KEY (premise_id) REFERENCES public.premises(id) ON DELETE CASCADE;

    -- 4. agent_ledger_entries
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'agent_ledger_entries_premiseId_fkey') THEN
        ALTER TABLE public.agent_ledger_entries DROP CONSTRAINT "agent_ledger_entries_premiseId_fkey";
    END IF;
    ALTER TABLE public.agent_ledger_entries 
    ADD CONSTRAINT "agent_ledger_entries_premiseId_fkey" 
    FOREIGN KEY ("premiseId") REFERENCES public.premises(id) ON DELETE CASCADE;

    -- 5. premise_blocks
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'premise_blocks_premiseId_fkey') THEN
        ALTER TABLE public.premise_blocks DROP CONSTRAINT "premise_blocks_premiseId_fkey";
    END IF;
    ALTER TABLE public.premise_blocks 
    ADD CONSTRAINT "premise_blocks_premiseId_fkey" 
    FOREIGN KEY ("premiseId") REFERENCES public.premises(id) ON DELETE CASCADE;

    -- 6. ratings
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'ratings_premiseId_fkey') THEN
        ALTER TABLE public.ratings DROP CONSTRAINT "ratings_premiseId_fkey";
    END IF;
    ALTER TABLE public.ratings 
    ADD CONSTRAINT "ratings_premiseId_fkey" 
    FOREIGN KEY ("premiseId") REFERENCES public.premises(id) ON DELETE CASCADE;

END $$;



-- ============================================================
-- MIGRATION: CONSOLIDATED_FINAL_SETUP.sql
-- ============================================================

-- =============================================================================
-- AAVIJA VMS — COMPLETE SYSTEM SETUP, OPTIMIZATION & POLICY CONSOLIDATION (V7)
-- Target: 100% Security Advisor Score & Scalability Refactor
-- Run this in Supabase SQL Editor
-- This script is idempotent (safe to run multiple times)
-- =============================================================================

-- 1. Create premise_gates table
CREATE TABLE IF NOT EXISTS public.premise_gates (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  premise_id  UUID NOT NULL REFERENCES public.premises(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  is_active   BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_premise_gates_premise ON public.premise_gates(premise_id);

-- 2. Create premise_members table
CREATE TABLE IF NOT EXISTS public.premise_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  premise_id  UUID NOT NULL REFERENCES public.premises(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role        TEXT NOT NULL CHECK (role IN ('host', 'gatekeeper')),
  identity    TEXT, -- Unit No / Flat No (primarily for hosts)
  gate_id     UUID REFERENCES public.premise_gates(id) ON DELETE SET NULL,
  is_active   BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE(premise_id, user_id, role)
);

CREATE INDEX IF NOT EXISTS idx_premise_members_premise ON public.premise_members(premise_id);
CREATE INDEX IF NOT EXISTS idx_premise_members_user    ON public.premise_members(user_id);
CREATE INDEX IF NOT EXISTS idx_premise_members_role    ON public.premise_members(role);

-- 3. Optimization: Missing Foreign Key Indexes
CREATE INDEX IF NOT EXISTS idx_cities_district_id ON public.cities("districtId");
CREATE INDEX IF NOT EXISTS idx_cities_state_id ON public.cities("stateId");
CREATE INDEX IF NOT EXISTS idx_districts_state_id ON public.districts("stateId");
CREATE INDEX IF NOT EXISTS idx_premise_members_gate_id ON public.premise_members(gate_id);
CREATE INDEX IF NOT EXISTS idx_premises_agent_id ON public.premises(agent_id);
CREATE INDEX IF NOT EXISTS idx_premises_owner_id ON public.premises(owner_id);
CREATE INDEX IF NOT EXISTS idx_ratings_visitor_id ON public.ratings("visitorId");

-- 4. Data Migration Script (JSONB -> Relational)
DO $$
DECLARE
    p_rec RECORD;
    s_item JSONB;
BEGIN
    FOR p_rec IN SELECT id, staff FROM public.premises WHERE staff IS NOT NULL AND jsonb_array_length(staff) > 0 LOOP
        FOR s_item IN SELECT jsonb_array_elements(p_rec.staff) LOOP
            INSERT INTO public.premise_members (premise_id, user_id, role, identity, is_active)
            VALUES (
                p_rec.id,
                (s_item->>'uid')::UUID,
                (s_item->>'role'),
                (s_item->>'identity'),
                COALESCE((s_item->>'is_active')::BOOLEAN, true)
            )
            ON CONFLICT (premise_id, user_id, role) DO NOTHING;
        END LOOP;
    END LOOP;
END $$;

-- 5. RPC & Function Hardening (Security & Performance)
CREATE OR REPLACE FUNCTION search_premise_members(
    premise_id_param UUID,
    role_param TEXT DEFAULT NULL,
    search_term_param TEXT DEFAULT '',
    limit_param INT DEFAULT 50,
    offset_param INT DEFAULT 0
)
RETURNS TABLE (
    id UUID, premise_id UUID, user_id UUID, role TEXT, identity TEXT, gate_id UUID,
    is_active BOOLEAN, created_at TIMESTAMPTZ, user_name TEXT, user_email TEXT, user_photo_url TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pm.id, pm.premise_id, pm.user_id, pm.role, pm.identity, pm.gate_id,
        pm.is_active, pm.created_at, u.name as user_name, u.email as user_email, u.photo_url as user_photo_url
    FROM premise_members pm
    JOIN users u ON pm.user_id = u.id
    WHERE pm.premise_id = premise_id_param
      AND (role_param IS NULL OR pm.role = role_param)
      AND (search_term_param = '' OR u.name ILIKE '%' || search_term_param || '%' OR u.email ILIKE '%' || search_term_param || '%' OR pm.identity ILIKE '%' || search_term_param || '%')
    ORDER BY pm.created_at DESC
    LIMIT limit_param OFFSET offset_param;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION increment_gatekeeper_count(premise_id_param UUID) RETURNS VOID AS $$
BEGIN UPDATE premises SET gatekeeper_count = COALESCE(gatekeeper_count, 0) + 1 WHERE id = premise_id_param; END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
CREATE OR REPLACE FUNCTION decrement_gatekeeper_count(premise_id_param UUID) RETURNS VOID AS $$
BEGIN UPDATE premises SET gatekeeper_count = GREATEST(0, COALESCE(gatekeeper_count, 0) - 1) WHERE id = premise_id_param; END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
CREATE OR REPLACE FUNCTION increment_host_count(premise_id_param UUID) RETURNS VOID AS $$
BEGIN UPDATE premises SET host_count = COALESCE(host_count, 0) + 1 WHERE id = premise_id_param; END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
CREATE OR REPLACE FUNCTION decrement_host_count(premise_id_param UUID) RETURNS VOID AS $$
BEGIN UPDATE premises SET host_count = GREATEST(0, COALESCE(host_count, 0) - 1) WHERE id = premise_id_param; END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 6. Add gate tracking to visits table
ALTER TABLE public.visits 
ADD COLUMN IF NOT EXISTS checkin_gate_id UUID REFERENCES public.premise_gates(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS checkout_gate_id UUID REFERENCES public.premise_gates(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_visits_checkin_gate ON public.visits(checkin_gate_id);
CREATE INDEX IF NOT EXISTS idx_visits_checkout_gate ON public.visits(checkout_gate_id);

-- 7. CLEAN SLATE: DYNAMICALLY DROP ALL LEGACY POLICIES
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename IN ('announcements', 'cities', 'districts', 'invoices', 'premise_categories', 'premise_gates', 'premise_members', 'premises', 'states')
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
    END LOOP;
END $$;

-- 8. RECREATE POLICIES (Optimized & Mutually Exclusive)
-- Patterns changed from FOR ALL to specific actions to avoid "Multiple Permissive Policies" warnings.

-- [TABLE: premise_gates]
ALTER TABLE public.premise_gates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "premise_gates_select" ON public.premise_gates FOR SELECT USING (true);
CREATE POLICY "premise_gates_insert" ON public.premise_gates FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));
CREATE POLICY "premise_gates_update" ON public.premise_gates FOR UPDATE USING (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));
CREATE POLICY "premise_gates_delete" ON public.premise_gates FOR DELETE USING (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));

-- [TABLE: premise_members]
ALTER TABLE public.premise_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "premise_members_select" ON public.premise_members FOR SELECT USING (true);
CREATE POLICY "premise_members_insert" ON public.premise_members FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));
CREATE POLICY "premise_members_update" ON public.premise_members FOR UPDATE USING (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));
CREATE POLICY "premise_members_delete" ON public.premise_members FOR DELETE USING (EXISTS (SELECT 1 FROM public.premises WHERE premises.id = premise_id AND premises.owner_id = (SELECT auth.uid())));

-- [TABLE: premises]
CREATE POLICY "premises_select" ON public.premises FOR SELECT USING (true);
CREATE POLICY "premises_insert" ON public.premises FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "premises_update" ON public.premises FOR UPDATE USING (owner_id = (SELECT auth.uid()) OR public.is_admin());
CREATE POLICY "premises_delete" ON public.premises FOR DELETE USING (public.is_admin());

-- [TABLE: premise_categories]
CREATE POLICY "premise_categories_select" ON public.premise_categories FOR SELECT USING (true);
CREATE POLICY "premise_categories_insert" ON public.premise_categories FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "premise_categories_update" ON public.premise_categories FOR UPDATE USING (public.is_admin());
CREATE POLICY "premise_categories_delete" ON public.premise_categories FOR DELETE USING (public.is_admin());

-- [TABLE: invoices]
CREATE POLICY "invoices_select" ON public.invoices FOR SELECT USING ("userId" = (SELECT auth.uid()) OR public.is_admin());
CREATE POLICY "invoices_insert" ON public.invoices FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "invoices_update" ON public.invoices FOR UPDATE USING (public.is_admin());
CREATE POLICY "invoices_delete" ON public.invoices FOR DELETE USING (public.is_admin());

-- [TABLE: announcements]
CREATE POLICY "announcements_select" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "announcements_insert" ON public.announcements FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "announcements_update" ON public.announcements FOR UPDATE USING (public.is_admin());
CREATE POLICY "announcements_delete" ON public.announcements FOR DELETE USING (public.is_admin());

-- [TABLE: cities]
CREATE POLICY "cities_select" ON public.cities FOR SELECT USING (true);
CREATE POLICY "cities_insert" ON public.cities FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "cities_update" ON public.cities FOR UPDATE USING (public.is_admin());
CREATE POLICY "cities_delete" ON public.cities FOR DELETE USING (public.is_admin());

-- [TABLE: districts]
CREATE POLICY "districts_select" ON public.districts FOR SELECT USING (true);
CREATE POLICY "districts_insert" ON public.districts FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "districts_update" ON public.districts FOR UPDATE USING (public.is_admin());
CREATE POLICY "districts_delete" ON public.districts FOR DELETE USING (public.is_admin());

-- [TABLE: states]
CREATE POLICY "states_select" ON public.states FOR SELECT USING (true);
CREATE POLICY "states_insert" ON public.states FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "states_update" ON public.states FOR UPDATE USING (public.is_admin());
CREATE POLICY "states_delete" ON public.states FOR DELETE USING (public.is_admin());

-- 9. GRANT ACCESS
GRANT ALL ON public.premise_gates TO service_role;
GRANT ALL ON public.premise_members TO service_role;
GRANT SELECT ON public.premise_gates TO authenticated;
GRANT SELECT ON public.premise_members TO authenticated;
GRANT ALL ON public.premise_gates TO postgres;
GRANT ALL ON public.premise_members TO postgres;


